# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Harry Huang
subtitle: Blog Site
description: Blog Site of Harry Huang
keywords: Harry Huang
author: Harry Huang
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.harryh.cn
root: /
permalink: :category/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: true
post_asset_folder: true
relative_link: false
future: false
# syntax_highlighter: highlight.js
# highlight:
#   auto_detect: false
#   line_number: true
#   line_threshold: 1
#   tab_replace: '  '
#   wrap: true
#   hljs: true
# syntax_highlighter: prismjs
# prismjs:
#   preprocess: true
#   line_number: true
#   line_threshold: 1
#   tab_replace: '  '

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  pagination_dir: page

# Category & Tag
default_category: Uncategorized
category_map:
tag_map:

# Date / Time format
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime' # 'mtime', 'date', 'empty'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions: Theme
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: redefine

# Extensions: Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/isHarryh/isharryh.github.io
  branch: gh-pages

# Extension: Metadata generator
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Include/exclude files or folders
## Options only apply to the 'source/' folder
include:
exclude:
ignore:

# Others: Markdown images
marked:
  prependRoot: true
  postAsset: true

# Others: MathJax settings
## Docs: https://redefine-docs.ohevan.com/en/plugins/mathjax
mathjax:
    tags: none # 'ams' or 'all'
    single_dollars: true
    cjk_width: 0.9
    normal_width: 0.6
    append_css: true
    every_page: true
